name: New File Request
description: Propose a list of CMIP6 datasets to be ingested to the cloud.
title: "New File Request [Dataset Name]"
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the Pangeo CMIP6 cloud data and making a request for additional data.
  - type: textarea
    id: file_list
    attributes:
        label: List of requested idds
        description: >
          To request new data, please create a list of instance_ids as strings which is copy-pasteable to python. You can use [pangeo-forge-esgf](https://github.com/jbusecke/pangeo-forge-esgf#parsing-a-list-of-instance-ids-using-wildcards) to make your life easier here.
        placeholder: >
            <details>
            ```python
            'CMIP6.CMIP.THU.CIESM.piControl.r1i1p1f1.Omon.uo.gn.v20200220',
            ...
            'CMIP6.CMIP.THU.CIESM.piControl.r1i1p1f1.Omon.vo.gn.v20200220',
            'CMIP6.CMIP.CNRM-CERFACS.CNRM-CM6-1-HR.historical.r1i1p1f2.Omon.so.gn.v20191021',
            ```
            <details/>
  - type: textarea
    id: comments
    attributes:
      label: Description
      description: >
        We cannot promise to deliver datasets on any timeline, but if you are looking to publish a paper soon, please make sure to mention it here, and we will do our best to process this request.
